### ISSUE TITLE
nodester app init app_name throws error

### ISSUE THREAD

**Issue by madhums** [nodester/nodester#142]
I was setting up my nodester hello world app and it threw the below error. But the app was created. 

<pre>
$nodester app init madhums
 ...
 ...
 Are you sure you want to continue connecting (yes/no)? yes
 nodester info clone complete
 nodester info writing app data to config
 nodester info writing app files
 nodester info processing the initial commit
 node: ../src/node.cc:1342: v8::Handle<v8::Value> node::Cwd(const v8::Arguments&): Assertion `args.Length() == 0' failed.
 Aborted
</pre>

**Comment by DanBUK** [comment]
I've pushed out version 0.2.15 of nodester-cli to fix this. Please npm install/update nodester-cli and re-test please; if fixed please close the issue.

**Comment by chrismatthieu** [comment]
I'm running node.js v0.4.8 on my localhost and nodester-cli 0.2.15 and get the following error on nodester app init:

christoffe:src christoffe$ nodester app init gangplank
nodester info initializing git repo for gangplank into folder gangplank
nodester info cloning the repo git clone ec2-user@nodester.com:/node/hosted_apps/topher/2667-286ed3c67eda650e41c6c1992e96783a.git gangplank
nodester info clone complete
nodester info writing app data to config

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor 'gangplank/.nodester.appconfig'
    at Object.openSync (fs.js:221:18)
    at Object.writeFileSync (fs.js:483:15)
    at Object.writeApp (/usr/local/lib/node/.npm/nodester-cli/0.2.15/package/lib/config.js:54:8)
    at /usr/local/lib/node/.npm/nodester-cli/0.2.15/package/lib/app.js:230:37
    at ChildProcess.exithandler (child_process.js:106:7)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)

I also re-ran user setup and setkey just to be sure. No dice.

**Comment by chrismatthieu** [comment]
i upgraded to nodejs v0.4.9 but that didnt help either.

**Comment by chrismatthieu** [comment]
App init works fine on 1 of my macs and not on my other.  I wonder if this is related to the passphrase issue on the RSA key.

**Comment by DanBUK** [comment]
Can you use an ssh-agent to test on the machine where it fails?

ssh-agent > ~/.agent.env
source ~/.agent.env
ssh-add <path to id_rsa or id_dsa>

Then you can add the source line to you ~/.bashrc or ~/.bash_profile then on reboot re run the agent and ssh-add lines.

**Comment by egilchri** [comment]
Hi. Would a good way to know when nodester is working for new app creation again, be, to monitor this thread? Thanks.

**Comment by DanBUK** [comment]
egilchri, App create is working server side, it is just there is a bug on the cli tools. So you can use:

nodester app create
nodester app clone

Then use git push to depoy.

**Comment by DanBUK** [comment]
I've just had this working a few times locally. Can you please ensure nodester-cli is updated on your and and re-try this. If it's fixed please post/close this issue.

**Comment by egilchri** [comment]
It seems to be working, and that's great. I'm a little perplexed, though, by the error I get when I do an init. But I'll close the issue because it may be must my error.

Last login: Mon Aug  1 11:13:14 on console
You have new mail.
edgar-gilchrists-macbook-2:~ egilchri$ script
Script started, output file is typescript
bash-3.2$ nodester app create egilchri005
nodester info creating app: egilchri005 server.js
nodester info successfully created app egilchri005 to will run on port 11149 from server.js
nodester info run nodester app init egilchri005 to setup this app.
bash-3.2$ nodester app init egilchri005
nodester info initializing git repo for egilchri005 into folder egilchri005
nodester info cloning the repo git clone git@nodester.com:/node/git/egilchri/2996-ec867899a4662911b9f08deb97be559d.git egilchri005
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR [HTTP 408] failure - application already running.
bash-3.2$

**Comment by egilchri** [comment]
Well, it looks like I don't have the permissions to close the issue. But, at any rate, I'm happy.

**Comment by DanBUK** [comment]
Yes the CLI needs updating to not attempt to start the app after the initial commit. The app is started by the initial commit :)
