### ISSUE TITLE
Does nodester supports npm install jquery or  jsdom

### ISSUE THREAD

**Issue by buzzshiva** [nodester/nodester#165]
Step 1:
$user@asd ~/appTest
  nodester npm install jsdom

Step2 :
added a small jsdom example into server.js
example: - http://snipt.org/xmqn

vi server.js 

Step3: 
git add . 
git commit . -m "new file"
git push 

Step 4:
when i try to run the test url  http://apptest.nodester.com/  
it throws this error. Am I missing something. How do i check if the install of jsdom went correct.

ERROR:-

An error has occurred: {"stack":"Error: ECONNREFUSED, Connection refused\n    at Socket._onConnect (net.js:601:18)\n    at IOWatcher.onWritable [as callback](net.js:186:12)","message":"ECONNREFUSED, Connection refused","errno":111,"code":"ECONNREFUSED","syscall":"connect"}

$ nodester npm install jsdom
nodester info installing to app: apptest
nodester info installing these npm packages: jsdom
nodester ├── request@2.0.1
nodester ├── cssom@0.2.0
nodester └── htmlparser@1.7.3
nodester

nodester warn you should restart your app after you are finished installing pack
ages.

user@asd ~/testApp/apptest
$

$ nodester app restart
nodester info Attemping to restart app: apptest
nodester info app restarted.

user@asd ~/testApp/apptest
$

**Comment by DanBUK** [comment]
Hi Buzzshiva, you script is running but it will only run and then exit cleanly. It's not setting up anything that listens for http requests.

Setup an http server and when you use the listen call use .listen(process.env['app_port']) and it will listen on the correct port so that requests for http://apptest.nodester.com/ will be forwarded onto it.
