### ISSUE TITLE
Using node-canvas: need to install some packages

### ISSUE THREAD

**Issue by xdamman** [nodester/nodester#237]
I would love to be able to use `canvas` in my app. For that to work some packages need to be installed (namely cairo and libjpeg8-dev)

```
$ sudo apt-get install libcairo2-dev libjpeg8-dev
```

Can you please do that?
Thanks.

See:
https://github.com/learnboost/node-canvas/wiki

**Comment by yocontra** [comment]
This has been opened before (and I believe it's still open somewhere...)

Basically the issue is that we need to include the packages in the user sandbox but before we do that we need to make sure there aren't any security issues within the packages. It may take us a while to do this but we're also working on a new sandbox where you can install anything you want that will probably be done first.
