### ISSUE TITLE
App stops for no apparent reason

### ISSUE THREAD

**Issue by eflorico** [nodester/nodester#253]
My app (http://updatified.nodester.com) seems to work fine generally. However, when I check back on it some time after doing development work, I frequently receive a _503 Application Offline_. `nodester app info` shows that the app is not running, however, there are no logs available:

```
> nodester app logs
nodester info { response: '{"status":"failure","message":"No logs available."}\n',
  errorCode: 500 }
nodester ERROR Fatal Error! API Response: {"status":"failure","message":"No logs available."}

Reason: No logs available.
```

The problem can be fixed temporarily by running `nodester app start`.

What could be the reason for this?

**Comment by chrismatthieu** [comment]
This may have been caused by us restarting the servers without restarting the apps properly.  You may also want to add the following error handling in your app to prevent the app from stopping due to errors encountered in your app:

process.on('uncaughtException', function(err) {
  console.log(err.stack);
});

**Comment by eflorico** [comment]
How often do you restart the servers? The app stopped again on January 4th. Interestingly, `nodester app info` reports `nodester info updatified on port 11547 running: true (pid: 360)`. The logs are empty as before.

**Comment by chrismatthieu** [comment]
We do not have a regular maintenance schedule currently.  We restarted the
servers on 1/4 due to out-of-memory errors.  We are working on a new
version of Nodester which should scale easier and allow us to split the
servers out with better sandboxing to hopefully prevent these types of
errors in the future.  There is currently no ETA on Nodester V2.

On Fri, Jan 6, 2012 at 4:25 PM, Eric Wolf <
reply@reply.github.com

**Comment by eflorico** [comment]
Alright, I can fully understand that maintenance is required, but I guess it shouldn't be very hard to restart the apps after the actual downtime has passed. The frequent unavailability of the app is quite annoying and, as of now, renders the app unusable to any actual users who cannot restart it from the terminal themselves. As an app owner I can't constantly check if my app is still running which leads to unnecessary downtimes for the users.
