### ISSUE TITLE
NPM Modules list action support?

### ISSUE THREAD

**Issue by uchiyama2000** [nodester/nodester#26]
how do i get installed module list? so, an APPNPM list action?

**Comment by zr0z** [comment]
Yes, I was thinking that an option to list which npm packages have been installed for a given app would be really great and handy. Something like :
    $ nodester npm list
which would launch a `npm list installed` for the given repository

**Comment by davglass** [comment]
The entire npm system needs to be "re-thought", now that the chroot is actually working properly and we are running on Node 0.4.0, we need a way to specify which version of npm we are using, we also need to install that version into the chroot and use it to install things from inside the chroot. Installing any module that compiles (canvas) will result in a dead module because the libs are outside the chroot. Also, the new npm (0.3.x) installs packages with a package.json file that contains full paths, which in a chroot environment is not a good thing.

**Comment by DanBUK** [comment]
This will be resolved with the newer chroot system planned in #143 which I am starting to test.

**Comment by DanBUK** [comment]
nodester.com / api / cli have all been updated with npm list support.
