### ISSUE TITLE
Important bug with the register form

### ISSUE THREAD

**Issue by cjoudrey** [nodester/nodester#35]
Hey guys,

I just tried registering for the beta. I managed to create a user but after testing with 3 accounts I noticed a pretty big issue with the register form.

I added the $ character to my password and it seems to be causing problems. It keeps saying the password is invalid.

I tried re-creating another account with the same password minus the $ character and it works fine.

I'm guessing this might be an encoding issue like the problem you are having with the RSA key (i.e. replace + with %2b).

Thanks!

**Comment by chrismatthieu** [comment]
$ is written to the database on registration as a hash.  The issue is on the CLI and the cURL to authenticate.  The $ must be replace as a \$.  The CLI has been update in push https://github.com/nodester/nodester-cli/commit/8820e68a2671fbaaf348b81ad6c12581063d5d56

Once we test and deploy, this issue can be closed.

**Comment by chrismatthieu** [comment]
My \$ update in the CLI didn't seem to fix this issue.  It works in the curl API calls.  I'll need to do more testing.

**Comment by chrismatthieu** [comment]
Just deployed updated validation to production to prevent symbols in password in UI and API
