### ISSUE TITLE
Need Access Specified to user repo

### ISSUE THREAD

**Issue by KITSVineetMore** [nodester/nodester#360]
Hi,

I need to know is there anyway to provide any access specifier to a particular repo. Like for example: 

There are three users A,B,C and i have a repo with three branches A1,B1,C1. then is there a way in GITHUB that i can provide access to the users A,B,C with particular set of files needed for them but they cannot access the files apart from the  files they are being given access to.

I will be grateful if anybody can help me in this regards.

Thanks in Advance.

Regards,
Vineet More

**Comment by alejandro** [comment]
That's a hard task, since you can give access to an entire repo to someone but not only parts or branch of your project, the same for nodester. Github allows multiples users over a single repo, so you can add your team member to the repo and then one people will be in charge of push it to nodester. At least that's what I think will be more useful for the scenario that you are saying. 

Cheers.

**Comment by alejandro** [comment]
No response
