### ISSUE TITLE
Newly created app fails when accessed

### ISSUE THREAD

**Issue by cjoudrey** [nodester/nodester#37]
When accessing http://mynodesterapp3.nodester.com/ it outputs the following message:

```
An error has occurred: {"message":"ECONNREFUSED, Connection refused","stack":"Error: ECONNREFUSED, Connection refused\n    at IOWatcher.callback (net:870:22)\n    at node.js:773:9","errno":111,"syscall":"connect"}
```

I have not modified the hello.js, simply init'd and started.

**Comment by cjoudrey** [comment]
This seems to be linked to my other bug report (https://github.com/nodester/nodester-cli/issues#issue/2).

The issue is when `app init` fails, nothing is pushed to the server, thus when you `app start` there is nothing to be runned.

Maybe we could have `app start` return an error when this happens? I.e. 'Could not launch hello.js'.

**Comment by chrismatthieu** [comment]
From troubleshooting last night.  We seemed to think that maybe this issue was related to init not being able to create directories on the localhost.  Could be a permissions error.  I could not replicate the problem on my Macs.

When I looked at their repo on nodester.com it was empty.  This may also suggest an RSA key issue - thus not being able to push the updates to nodester.

**Comment by cjoudrey** [comment]
Confirmed, this is a problem with RSA key.

I regenerated my key and ran `app user setkey` and everything works fine.

**Comment by chrismatthieu** [comment]
Thanks for the update!
