### ISSUE TITLE
Files created not showing up in git

### ISSUE THREAD

**Issue by huffn** [nodester/nodester#376]
I've created a file in the /app folder,

``` javascript
fs.open(__dirname + "/test.txt", 'a', 0666, function(err, fd){
 fs.write(fd, query + "\n", null, undefined, function (err, written) {
 console.log('bytes written: ' + written);
  });
});
```

But I can't seem to access that file when I pull the project in git. What am I supposed to do in order to see test.txt?

**Comment by alejandro** [comment]
Since the path where your app lives can't access to the git repo (the original), you can't do `git add; git commit`. So, because the file is not inside the repo, you can't pull it back.

What you can do is to create a endpoint in your app's api to pull that file on request. Maybe something like:

``` javascript
// app logic code
if (req.url === '/test.txt'){
  var stream = fs.createReadStream('path/to/test.txt');
  stream.pipe(res);
}
// continue
```

And there you go, you can have your `test.txt` file locally, if that's what you want.

**Comment by alejandro** [comment]
RE: #313
