### ISSUE TITLE
Websockets not supported through Socket.io

### ISSUE THREAD

**Issue by tsenart** [nodester/nodester#47]
They get dropped to xhr-polling even if I have websockets enabled. 
Logs: https://gist.github.com/41818db314c949435693

**Comment by koto** [comment]
I encountered very similar issue on socket.io based app.

On the client, when I force the socket.io transport to be 'websocket' - the browser never receives any updated from the sent websockets handshake (server is a black hole)

However, when I change it to xhr-multipart, all works correctly.

**Comment by koto** [comment]
I think it's because nodester uses lib/3rdparty/node-http-proxy.js file to forward requests from port 80 to appropriate app. WebSockets requests are not HTTP requests (although they look very similar) , so they are either stripped (and become invalid in the target app) or not handled at all by the proxy.

I don't have the infrastructure to test this, but it looks as there needs to be some special handling for WebSockets traffic to be forwarded correctly.

**Comment by davglass** [comment]
This should be working now, can you test it now to make sure?

**Comment by nodester** [comment]
IT TOTALLY WORKS!  Check out http://chat.nodester.com as well as our new blog post http://nodester.tumblr.com/post/3634535277/running-websockets-on-nodester

**Comment by koto** [comment]
I confirm, everything works perfectly! Thanks!

**Comment by mkilling** [comment]
It seems the problem has reappeared. socket.io falls back to XHR polling. Possibly related: The chat example at http://chat.nodester.com is stuck at 'connecting'.

**Comment by moduleitor** [comment]
...  http://chat.nodester.com it's not working!!!

**Comment by nodester** [comment]
That was my bad. I didn't have my chat app running. Just restarted it for
you.

-Chris

On Thu, Apr 5, 2012 at 3:58 AM, moduleitor <
reply@reply.github.com
