### ISSUE TITLE
Support adding custom SSL certs for appdomains

### ISSUE THREAD

**Issue by abraham** [nodester/nodester#57]
if app example has a custom domain of example.com it would be awesome if I could buy a SSL cert for https://example.com to use with nodester.

**Comment by toxik** [comment]
From what I know that's not possible cross-browser if nodester only uses one public IP address (which is probably the case).
That's because of how HTTPS was made from its very beginning, doesn't have to do with anything else - like server configuration for example.

There is a solution though, but it's not that great - http://en.wikipedia.org/wiki/Server_Name_Indication - because of limited browser and server support AND because it's less secure ( encryption starts later than normal ).

**Comment by DanBUK** [comment]
SNI is not less secure, it means the HTTP Host header is sent along with the SSL  handshake request, therefore a server can present the appropriate certificate. I don't currently know the status of SNI support in node.js. Once it is in place 1 IP can handle the multiple apps of nodester.

The alternative is to spin up more public IP addresses, but I believe ec2 charges per IP so could become costly..

**Comment by yocontra** [comment]
Closed due to absence from V2 roadmap.
