### ISSUE TITLE
nodester npm install fails

### ISSUE THREAD

**Issue by janewilkin** [nodester/nodester#71]
I have been unable to install npm packages to my new app, which I named albumtross.  I always get the same error, which I have pasted a few examples of below.  

garrett@Bunty:~/github/albumtross$ nodester npm install itunes
nodester info Checking config..
nodester ERRO no packages to install

garrett@Bunty:~/github/albumtross$ nodester npm install vows
nodester info Checking config..
nodester ERRO no packages to install

garrett@Bunty:~/github/albumtross$ nodester npm install socket.io
nodester info Checking config..
nodester ERRO no packages to install

**Comment by davglass** [comment]
What version of node? What OS?

**Comment by janewilkin** [comment]
I am running these versions of locally:

node@v0.5.0-pre
npm@0.2.13-3

But my local version of node should not affect this nodester command, should it?  Isn't that all remote based?  Or is it an issue because the nodester client itself is written in node?

I am running Ubuntu 10.10

**Comment by davglass** [comment]
The npm part doesn't matter, but that error means that the nodester-cli couldn't find the arguments passed to it. And yes, the nodester-cli is written in node so the Node version matters.

**Comment by jrosenthal** [comment]
Shouldn't it be :
nodester npm install <app-name> <package-name>
ie: nodester npm install albumtross socket.io 
as per http://nodester.com/api.html#clicommands

[nodester npm] seems to suggest syntax without app-name which didn't work for me either.

**Comment by janewilkin** [comment]
I just switched to hosting at linode and figured I would come back when
things were running a little more smoothly :)

Garrett Wilkin

**Comment by chrismatthieu** [comment]
We performed updates on the system today.  Could you try it again?

**Comment by chrismatthieu** [comment]
unable to duplicate

**Comment by snelis** [comment]
Im reopening this because i had the same issue and have clarification.

$ nodester npm
nodester All arguments after install|update|uninstall will be sent to npm as packages.
nodester npm install < packages > - Installs the list of specified packages to this app.
nodester npm update < packages > - Update the list of specified packages to this app.
nodester npm uninstall < packages > - Removes the list of specified packages to this app.

As you can see these commands state to do the following:

$ nodester npm install socket.io

Which will give:
$ nodester ERROR no packages to install

So actually the manual ($ nodester npm) should state the correct way:
$ nodester npm install < app_name > < packages > - Installs the list of specified packages to this app.
